departments = {
    "BME":"BME . . . . . . . . Biomedical Engineering",
    "CHEM":"CHEM . . . . . . .Chemistry",
    "CHEMISTRY":"CHEM . . . . . . .Chemistry",
    "CS":"COMPSCI . . . . Computer Science",
    "COMPSCI":"COMPSCI . . . . Computer Science",
    "CSE":"CSE . . . . . . . . Computer Science and Engineering",
    "EECS":"EECS . . . . . . . Electrical Engineering & Computer Science",
    "EE":"EECS . . . . . . . Electrical Engineering & Computer Science",
    "ENGRCEE":"ENGRCEE . . . .Engineering, Civil and Environmental",
    "CEE":"ENGRCEE . . . .Engineering, Civil and Environmental",
    "CE":"ENGRCEE . . . .Engineering, Civil and Environmental",
    "ENGRMAE":"ENGRMAE . . . .Engineering, Mechanical and Aerospace",
    "MAE":"ENGRMAE . . . .Engineering, Mechanical and Aerospace",
    "ME":"ENGRMAE . . . .Engineering, Mechanical and Aerospace",
    "I&C SCI":"I&C SCI . . . . . . Information and Computer Science",
    "I&CSCI":"I&C SCI . . . . . . Information and Computer Science",
    "ICS":"I&C SCI . . . . . . Information and Computer Science",
    "IN4MATX":"IN4MATX . . . . . Informatics",
    "IN4":"IN4MATX . . . . . Informatics",
    "MATH":"MATH . . . . . . . Mathematics",
    "MSE":"MSE . . . . . . . . Materials Science and Engineering (started 2020 Fall)",
    "PHYSICS":"PHYSICS . . . . .Physics",
    "PHYS":"PHYSICS . . . . .Physics",
    "STATS":"STATS . . . . . . .Statistics",
    "STAT":"STATS . . . . . . .Statistics"
}

course_names = {
    "BME":"BmE    ",
    "CHEM":"Chem   ",
    "CHEMISTRY":"Chem   ",
    "CS":"CompSci",
    "COMPSCI":"CompSci",
    "CSE":"CSE    ",
    "EECS":"EECS   ",
    "EE":"EECS   ",
    "ENGRCEE":"EngrCEE",
    "CEE":"EngrCEE",
    "CE":"EngrCEE",
    "ENGRMAE":"EngrMAE",
    "MAE":"EngrMAE",
    "ME":"EngrMAE",
    "I&C SCI":"I&C Sci",
    "I&CSCI":"I&C Sci",
    "ICS":"I&C Sci",
    "IN4MATX":"In4matx",
    "IN4":"In4matx",
    "MATH":"Math   ",
    "MSE":"MSE ",
    "PHYSICS":"Physics",
    "PHYS":"Physics",
    "STATS":"Stats  ",
    "STAT":"Stats  "
}